# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connect.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='connect.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rconnect.proto\"3\n\x0bHelloServer\x12\x10\n\x08WorkerIp\x18\x01 \x01(\t\x12\x12\n\nWorkerPort\x18\x02 \x01(\t\"#\n\x0bHelloWorker\x12\x14\n\x0c\x43onfirmation\x18\x01 \x01(\x08\x32\x38\n\x07\x43onnect\x12-\n\rConnectServer\x12\x0c.HelloServer\x1a\x0c.HelloWorker\"\x00\x62\x06proto3')
)




_HELLOSERVER = _descriptor.Descriptor(
  name='HelloServer',
  full_name='HelloServer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='WorkerIp', full_name='HelloServer.WorkerIp', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='WorkerPort', full_name='HelloServer.WorkerPort', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=68,
)


_HELLOWORKER = _descriptor.Descriptor(
  name='HelloWorker',
  full_name='HelloWorker',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Confirmation', full_name='HelloWorker.Confirmation', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=105,
)

DESCRIPTOR.message_types_by_name['HelloServer'] = _HELLOSERVER
DESCRIPTOR.message_types_by_name['HelloWorker'] = _HELLOWORKER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloServer = _reflection.GeneratedProtocolMessageType('HelloServer', (_message.Message,), dict(
  DESCRIPTOR = _HELLOSERVER,
  __module__ = 'connect_pb2'
  # @@protoc_insertion_point(class_scope:HelloServer)
  ))
_sym_db.RegisterMessage(HelloServer)

HelloWorker = _reflection.GeneratedProtocolMessageType('HelloWorker', (_message.Message,), dict(
  DESCRIPTOR = _HELLOWORKER,
  __module__ = 'connect_pb2'
  # @@protoc_insertion_point(class_scope:HelloWorker)
  ))
_sym_db.RegisterMessage(HelloWorker)



_CONNECT = _descriptor.ServiceDescriptor(
  name='Connect',
  full_name='Connect',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=107,
  serialized_end=163,
  methods=[
  _descriptor.MethodDescriptor(
    name='ConnectServer',
    full_name='Connect.ConnectServer',
    index=0,
    containing_service=None,
    input_type=_HELLOSERVER,
    output_type=_HELLOWORKER,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONNECT)

DESCRIPTOR.services_by_name['Connect'] = _CONNECT

# @@protoc_insertion_point(module_scope)
