# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import connect_pb2 as connect__pb2


class ConnectStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ConnectServer = channel.unary_unary(
        '/Connect/ConnectServer',
        request_serializer=connect__pb2.HelloServer.SerializeToString,
        response_deserializer=connect__pb2.HelloWorker.FromString,
        )


class ConnectServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ConnectServer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ConnectServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ConnectServer': grpc.unary_unary_rpc_method_handler(
          servicer.ConnectServer,
          request_deserializer=connect__pb2.HelloServer.FromString,
          response_serializer=connect__pb2.HelloWorker.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Connect', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
