# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scan.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='scan.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nscan.proto\".\n\x0bScanRequest\x12\x0f\n\x07IpRange\x18\x01 \x01(\t\x12\x0e\n\x06Modulo\x18\x02 \x01(\t\" \n\x0cScanResponse\x12\x10\n\x08Resposta\x18\x01 \x01(\t\"$\n\x12\x44\x65scriptionRequest\x12\x0e\n\x06Modulo\x18\x01 \x01(\t\"*\n\x13\x44\x65scriptionResponse\x12\x13\n\x0b\x44\x65scription\x18\x01 \x01(\t\",\n\x0eModulesRequest\x12\x1a\n\x12RequestModulesName\x18\x01 \x01(\t\"\"\n\nModuleList\x12\x14\n\x0cModulesNames\x18\x01 \x03(\t2\x9e\x01\n\x04Scan\x12>\n\x0fScanDescription\x12\x13.DescriptionRequest\x1a\x14.DescriptionResponse\"\x00\x12\'\n\x06ScanIp\x12\x0c.ScanRequest\x1a\r.ScanResponse\"\x00\x12-\n\x0bListModules\x12\x0f.ModulesRequest\x1a\x0b.ModuleList\"\x00\x62\x06proto3')
)




_SCANREQUEST = _descriptor.Descriptor(
  name='ScanRequest',
  full_name='ScanRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='IpRange', full_name='ScanRequest.IpRange', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Modulo', full_name='ScanRequest.Modulo', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=60,
)


_SCANRESPONSE = _descriptor.Descriptor(
  name='ScanResponse',
  full_name='ScanResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Resposta', full_name='ScanResponse.Resposta', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=94,
)


_DESCRIPTIONREQUEST = _descriptor.Descriptor(
  name='DescriptionRequest',
  full_name='DescriptionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Modulo', full_name='DescriptionRequest.Modulo', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=132,
)


_DESCRIPTIONRESPONSE = _descriptor.Descriptor(
  name='DescriptionResponse',
  full_name='DescriptionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Description', full_name='DescriptionResponse.Description', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=176,
)


_MODULESREQUEST = _descriptor.Descriptor(
  name='ModulesRequest',
  full_name='ModulesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='RequestModulesName', full_name='ModulesRequest.RequestModulesName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=222,
)


_MODULELIST = _descriptor.Descriptor(
  name='ModuleList',
  full_name='ModuleList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ModulesNames', full_name='ModuleList.ModulesNames', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=258,
)

DESCRIPTOR.message_types_by_name['ScanRequest'] = _SCANREQUEST
DESCRIPTOR.message_types_by_name['ScanResponse'] = _SCANRESPONSE
DESCRIPTOR.message_types_by_name['DescriptionRequest'] = _DESCRIPTIONREQUEST
DESCRIPTOR.message_types_by_name['DescriptionResponse'] = _DESCRIPTIONRESPONSE
DESCRIPTOR.message_types_by_name['ModulesRequest'] = _MODULESREQUEST
DESCRIPTOR.message_types_by_name['ModuleList'] = _MODULELIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ScanRequest = _reflection.GeneratedProtocolMessageType('ScanRequest', (_message.Message,), dict(
  DESCRIPTOR = _SCANREQUEST,
  __module__ = 'scan_pb2'
  # @@protoc_insertion_point(class_scope:ScanRequest)
  ))
_sym_db.RegisterMessage(ScanRequest)

ScanResponse = _reflection.GeneratedProtocolMessageType('ScanResponse', (_message.Message,), dict(
  DESCRIPTOR = _SCANRESPONSE,
  __module__ = 'scan_pb2'
  # @@protoc_insertion_point(class_scope:ScanResponse)
  ))
_sym_db.RegisterMessage(ScanResponse)

DescriptionRequest = _reflection.GeneratedProtocolMessageType('DescriptionRequest', (_message.Message,), dict(
  DESCRIPTOR = _DESCRIPTIONREQUEST,
  __module__ = 'scan_pb2'
  # @@protoc_insertion_point(class_scope:DescriptionRequest)
  ))
_sym_db.RegisterMessage(DescriptionRequest)

DescriptionResponse = _reflection.GeneratedProtocolMessageType('DescriptionResponse', (_message.Message,), dict(
  DESCRIPTOR = _DESCRIPTIONRESPONSE,
  __module__ = 'scan_pb2'
  # @@protoc_insertion_point(class_scope:DescriptionResponse)
  ))
_sym_db.RegisterMessage(DescriptionResponse)

ModulesRequest = _reflection.GeneratedProtocolMessageType('ModulesRequest', (_message.Message,), dict(
  DESCRIPTOR = _MODULESREQUEST,
  __module__ = 'scan_pb2'
  # @@protoc_insertion_point(class_scope:ModulesRequest)
  ))
_sym_db.RegisterMessage(ModulesRequest)

ModuleList = _reflection.GeneratedProtocolMessageType('ModuleList', (_message.Message,), dict(
  DESCRIPTOR = _MODULELIST,
  __module__ = 'scan_pb2'
  # @@protoc_insertion_point(class_scope:ModuleList)
  ))
_sym_db.RegisterMessage(ModuleList)



_SCAN = _descriptor.ServiceDescriptor(
  name='Scan',
  full_name='Scan',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=261,
  serialized_end=419,
  methods=[
  _descriptor.MethodDescriptor(
    name='ScanDescription',
    full_name='Scan.ScanDescription',
    index=0,
    containing_service=None,
    input_type=_DESCRIPTIONREQUEST,
    output_type=_DESCRIPTIONRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ScanIp',
    full_name='Scan.ScanIp',
    index=1,
    containing_service=None,
    input_type=_SCANREQUEST,
    output_type=_SCANRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListModules',
    full_name='Scan.ListModules',
    index=2,
    containing_service=None,
    input_type=_MODULESREQUEST,
    output_type=_MODULELIST,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SCAN)

DESCRIPTOR.services_by_name['Scan'] = _SCAN

# @@protoc_insertion_point(module_scope)
