# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import scan_pb2 as scan__pb2


class ScanStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ScanDescription = channel.unary_unary(
        '/Scan/ScanDescription',
        request_serializer=scan__pb2.DescriptionRequest.SerializeToString,
        response_deserializer=scan__pb2.DescriptionResponse.FromString,
        )
    self.ScanIp = channel.unary_unary(
        '/Scan/ScanIp',
        request_serializer=scan__pb2.ScanRequest.SerializeToString,
        response_deserializer=scan__pb2.ScanResponse.FromString,
        )
    self.ListModules = channel.unary_unary(
        '/Scan/ListModules',
        request_serializer=scan__pb2.ModulesRequest.SerializeToString,
        response_deserializer=scan__pb2.ModuleList.FromString,
        )


class ScanServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ScanDescription(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ScanIp(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListModules(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ScanServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ScanDescription': grpc.unary_unary_rpc_method_handler(
          servicer.ScanDescription,
          request_deserializer=scan__pb2.DescriptionRequest.FromString,
          response_serializer=scan__pb2.DescriptionResponse.SerializeToString,
      ),
      'ScanIp': grpc.unary_unary_rpc_method_handler(
          servicer.ScanIp,
          request_deserializer=scan__pb2.ScanRequest.FromString,
          response_serializer=scan__pb2.ScanResponse.SerializeToString,
      ),
      'ListModules': grpc.unary_unary_rpc_method_handler(
          servicer.ListModules,
          request_deserializer=scan__pb2.ModulesRequest.FromString,
          response_serializer=scan__pb2.ModuleList.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Scan', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
